import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../globals.scss';
import Navbar from '@/components/Navbar/Navbar';
import localFont from 'next/font/local';
import Cursor from '@/components/Cursor/Cursor';
import SmoothScroll from '@/components/SmoothScroll/SmoothScroll';
import { MenuProvider } from '@/components/Navbar/MenuContext/MenuContext';
import Menu from '@/components/Navbar/Menu/Menu';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { getMessages } from 'next-intl/server';

// Font types
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '100'],
  variable: '--poppins',
  display: 'swap',
});
const eiko = localFont({
  src: [
    {
      path: '../../public/font/eiko-thin.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/font/eiko-medium.ttf',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--eiko',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Body
type PropsType = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<PropsType>) {
  // @ts-ignore
  const navMessages = useMessages('nav');
  const navFallback = {
    contact: 'Contact us',
    email: 'info@betalab.cloud',
    theme: 'Toggle theme',
    links: {
      home: 'Home',
      work: 'Our Work',
      services: 'Services',
      contact: 'Contact Us',
    },
  };

  return (
    <html lang={locale} className={`${eiko.variable} ${poppins.variable}`}>
      <body>
        <Cursor />
        <SmoothScroll />

        {/* Main */}
        <NextIntlClientProvider messages={navMessages as any}>
          <MenuProvider>
            <Navbar navFallback={navFallback} />
            <Menu navFallback={navFallback.links} />
          </MenuProvider>
        </NextIntlClientProvider>
        {children}
      </body>
    </html>
  );
}
