import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../globals.scss';
import Navbar from '@/components/Navbar/Navbar';
import localFont from 'next/font/local';

// Font types
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});
const eiko = localFont({
  src: [
    {
      path: '../../public/font/eiko-thin.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/font/eiko-medium.ttf',
      weight: '500',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className} ${eiko.className}`}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
